name: build_feature_navigator_and_filter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/apink/
    - assets/images/apink/
    - assets/images/g-friend/
    - assets/images/blackpink/
    - assets/images/twice/

flutter_native_splash:
  background_image: assets/images/Splash.jpg
  android_12:
    image: assets/images/Splash.jpg
  fullscreen: true