import '../models/idolKorean_model.dart';

class IdolkoreanRepository {
  List<Idolkorean> getItems() {
    List<Map<String, String>> itemsData = [
      {'name': 'Jisoo', 'image': 'assets/images/blackpink/1.jpg', 'group': 'BlackPink', 'link': 'Jisoo','description': 'Kim Ji-soo (Korean: 김지수; born January 3, 1995), better known by her stage name Jisoo, is a South Korean singer and actress. She is best known as a member of the South Korean girl group Blackpink, formed and managed by YG Entertainment.'},
      {'name': 'Rosé', 'image': 'assets/images/blackpink/2.jpg', 'group': 'BlackPink', 'link': 'Jennie_(ca_sĩ)', 'description': 'Roseanne Park (born 11 February 1997), better known by the mononym Rosé, is a New Zealand singer based in South Korea. She is a member of the South'},
      {'name': 'Lisa', 'image': 'assets/images/blackpink/3.jpg', 'group': 'BlackPink', 'link': 'Rosé_(ca_sĩ)', 'description': 'Lalisa Manobal ( Thai : ลลิษา มโนบาล ) [ a ] [ 1 ] [ 2 ] [ 3 ] (birth name Pranpriya Manobal ( Thai : ปราณปรียา มโนบาล ); [ b ] [ 4 ] born March 27, 1997), commonly known by her stage name Lisa ( Korean : 리사 ), [ c ] is a Thai rapper, singer, songwriter and dancer . She is the youngest member of the South Korean girl group Blackpink under YG Entertainment . [ 5 ] In 2024, Lisa founded her own management company called LLOUD and signed with RCA Records . She is expected to make her acting debut in 2025 in the HBO drama The White Lotus .'},
      {'name': 'Jennie', 'image': 'assets/images/blackpink/4.jpg', 'group': 'BlackPink', 'link': 'Lisa_(rapper)', 'description': 'Jennie Kim ( Korean :  김제니 ; born January 16, 1996), better known by her stage name Jennie ( Korean :  제니 ; RR :  Jeni , homophone for her name) or Jennie Kim , is a South Korean singer , rapper , and actress . She is a member of the girl group Blackpink under YG Entertainment . In 2022, she will have her first acting role in the HBO drama The Idol , under the stage name Jennie Ruby Jane . In November 2023, Jennie founded her own label, Odd Atelier.'},
      {'name': 'Park Cho-rong', 'image': 'assets/images/apink/1.jpg', 'group': 'APink', 'link': 'Park_Cho-rong', 'description': 'Park Cho-rong ( Hangul : 박초롱, Han-Viet : Phác Sơ Lung), born March 3, 1991, is a South Korean idol singer, actress and songwriter . She is the leader of the girl group A Pink and under IST Entertainment , as a main rapper and sub-vocalist in the group.'},
      {'name': 'Yoon Bo-mi', 'image': 'assets/images/apink/2.jpg', 'group': 'APink','link': 'Yoon_Bo-mi', 'description': 'Yoon Bo-mi (Hangul: 윤보미, Hanja : 尹普美, Han-Viet : Doãn Phổ Mỹ, born August 13, 1993) is a South Korean idol singer, actress and host . She is a member of the girl group Apink managed by IST Entertainment and a member of the sub-group Apink BnN with Namjoo .'},
      {'name': 'Jung Eun-ji', 'image': 'assets/images/apink/3.jpg', 'group': 'APink', 'link': 'Jung_Eun-ji', 'description': 'Jung Hye-rim ( Hangul : 정혜림, Hanja : 郑慧林, Han-Vietnamese : Trinh Tue Lam, born August 18 , 1993 ) , later changed to Jung Eun-ji ( Hangul : 정은지, Hanja : 郑恩地, Han-Vietnamese : Trinh An Dia), commonly known by her stage name Eunji , is a South Korean singer , songwriter and actress . She is known as a member of the girl group Apink managed by IST Entertainment .'},
      {'name': 'Kim Nam-joo', 'image': 'assets/images/apink/4.jpg', 'group': 'APink', 'link': 'Kim_Nam-joo_(ca_sĩ)', 'description': 'Kim Nam-joo  ( Hangul : 김남주, Hanja : 金南珠, Han-Viet : Kim Nam Chau, born April 15 , 1995 ) is a South Korean idol singer and actress . She is a member of the girl group Apink and its subgroup Apink BnN with Yoon Bo-mi, formed and managed by IST Entertainment . She also officially launched a cosmetics brand called Pure Theory.'},
      {'name': 'Oh Ha-young', 'image': 'assets/images/apink/5.jpg', 'group': 'APink', 'link': 'Oh_Ha-young', 'description': 'Oh Ha-young  ( Hangul : 오하영, Hanja : 吳夏榮, Sino-Vietnamese : Ngô Hà Anh, born July 19, 1996), is a South Korean idol singer and songwriter . She is the youngest member of the South Korean girl group Apink , formed and managed by IST Entertainment .'},
      {'name': 'Sowon', 'image': 'assets/images/g-friend/1.jpg', 'group': 'G-Friend','link': 'Kim_So-won', 'description': 'Kim So-jeong (Korean:  김소정 )}; born December 7 , 1995 ) , commonly known by her former stage name  Sowon (Korean:  소원 ) or Kim So-won ( Korean :  김소원 ), is a South Korean singer and actress. She is a former member of the girl group GFriend .'},
      {'name': 'Yerin', 'image': 'assets/images/g-friend/2.jpg', 'group': 'G-Friend','link': 'Jung_Ye-rin', 'description': 'Jung Ye-rin ( Korean :  정예린 ; born August 19 , 1996 ) , better known by her stage name Yerin (Korean:  예린 ), is a South Korean singer and actress. She is a former member of the girl group GFriend .'},
      {'name': 'Eunha', 'image': 'assets/images/g-friend/3.jpg', 'group': 'G-Friend','link': 'Eunha', 'description': 'Jung Eun-bi ( Korean :  정은비 ; born May 30 , 1997 ) , better known by her stage name Eunha (Korean:  은하 ), is a South Korean singer and actress. She is a former member of the girl group GFriend and is currently a member of the girl group Viviz '},
      {'name': 'Yuju', 'image': 'assets/images/g-friend/4.jpg', 'group': 'G-Friend','link': 'Yuju', 'description': 'Choi Yu-na ( Korean :  최유나 ; born October 4 , 1997 ) , better known by her stage name Yuju (Korean:  유주 ), is a South Korean singer and songwriter. She is a former member of the girl group GFriend .'},
      {'name': 'SinB', 'image': 'assets/images/g-friend/5.jpg', 'group': 'G-Friend','link': 'SinB', 'description': 'Hwang Eun-bi ( Korean :  황은비 ; born June 3 , 1998 ) , [ 1 ] better known by her stage name SinB (Korean:  신비 ), is a South Korean singer, dancer, and actress. She is a former member of the girl group GFriend and is currently a member of the girl group Viviz .'},
      {'name': 'Umji', 'image': 'assets/images/g-friend/6.jpg', 'group': 'G-Friend','link': 'Umji', 'description': 'Kim Ye-won ( Korean :  김예원 ; born August 19 , 1998 ) , better known by her stage name Umji (Korean:  엄지 ), is a South Korean singer and dancer. She is a former member of the girl group GFriend and is currently a member of the girl group Viviz .'},
      {'name': 'Nayeon', 'image': 'assets/images/twice/1.jpg', 'group': 'Twice','link': 'Nayeon', 'description': 'Im Na-yeon (born September 22, 1995), better known by her stage name Nayeon , is a South Korean singer . After participating in the survival show Sixteen in 2015, she became a member of the girl group Twice under JYP Entertainment . [ 1 ] For two consecutive years (2017–2018), she was voted the sixth most popular idol in South Korea according to Gallup Korea\'s annual music poll.'},
      {'name': 'Jeongyeon', 'image': 'assets/images/twice/2.jpg', 'group': 'Twice','link': 'Yoo_Jeong-yeon', 'description': 'Yoo Kyeong-wan ( Korean :  유경완 ), later changed to Yoo Jeong-yeon ( Korean :  유정연 ; born [November 1, 1996], better known by her stage name Jeongyeon ( Korean :  정연 ), is a South Korean singer . She is a member of Twice , a South Korean girl group formed and managed by JYP Entertainment .'},
      {'name': 'Momo', 'image': 'assets/images/twice/3.jpg', 'group': 'Twice','link': 'Hirai_Momo', 'description': 'Hirai Momo ( Hangul : 히라이 모모, Hanja : 平井莫莫, Kanji : 平井桃, Kana : ひらい もも, Sino-Vietnamese : Bình Tĩnh Đào, born November 9 , 1996 ) , [ 1 ] commonly known by her stage name Momo , is a Japanese singer and dancer . She is a member of the South Korean girl group Twice and its subgroup MISAMO , formed and managed by JYP Entertainment .'},
      {'name': 'Sana', 'image': 'assets/images/twice/4.jpg', 'group': 'Twice','link': 'Minatozaki_Sana', 'description': 'Minatozaki Sana ( Hangul : 미나토자키 사나, Kanji : 湊崎紗夏, Kana : みなとざき さな, Sino-Vietnamese : Thấu Kỳ Sa Hạ, born December 29, 1996), [ 1 ] commonly known by her stage name Sana ( Hangul : 사나), is a Japanese female singer . She is known as a member of the Korean girl group TWICE along with the sub-group MISAMO formed and managed by JYP Entertainment .'},
      {'name': 'Jihyo', 'image': 'assets/images/twice/5.jpg', 'group': 'Twice','link': 'Park_Ji-hyo', 'description': 'Park Ji-hyo ( Hangul : 박지효, Hanja : 朴志效, Han-Vietnamese : Phác Chí Hiếu, born February 1 , 1997 ) , formerly known as Park Ji-soo ( Hangul : 박지수, Hanja : 朴智秀, Han-Vietnamese : Phác Trí Tú), commonly known by her stage name Jihyo , is a South Korean female singer , leader and main vocalist of the girl group Twice founded and managed by JYP Entertainment .'},
      {'name': 'Mina', 'image': 'assets/images/twice/6.jpg', 'group': 'Twice','link': 'Myoui_Mina', 'description': 'Myoui Mina ( Hangul : 묘이 미나, Kanji : 名井南; Kana : ミョウイミナ, Sino-Vietnamese : Danh Tinh Nam, born March 24 , 1997 ) , known by her stage name Mina ( Hangul : 미나) is a Japanese female idol singer , a member of the Korean girl group TWICE and TWICE \'s sub-unit MISAMO, founded and managed by JYP Entertainment . '},
      {'name': 'Dahyun', 'image': 'assets/images/twice/7.jpg', 'group': 'Twice','link': 'Kim_Da-hyun', 'description': 'Kim Da-hyun ( Hangul : 김다현, Hanja : 金多賢, Han-Viet : Kim Đa Hiền, born May 28 , 1998 ) , commonly known by her stage name Dahyun (Hangul: 다현), is a South Korean singer , rapper, dancer and actress . She is known as a member of the girl group Twice through the reality TV show Sixteen founded and managed by JYP Entertainment . '},
      {'name': 'Chaeyoung', 'image': 'assets/images/twice/8.jpg', 'group': 'Twice','link': 'Son_Chae-young', 'description': 'Son Chae-young ( Hangul : 손채영; Hanja : 孫彩瑛; Sino-Vietnamese : Tôn Thái Anh; born April 23, 1999), commonly known by her stage name Chaeyoung , is a South Korean female idol singer and rapper , a member of the girl group Twice formed by JYP Entertainment through the reality show SIXTEEN in 2015.'},
      {'name': 'Tzuyu', 'image': 'assets/images/twice/9.jpg', 'group': 'Twice','link': 'Chu_Tử_Du', 'description': 'Chou Tzu-yu or Chou Tzu-yu [ 2 ]  ( Chinese :周子瑜; pinyin : Zhōu Zǐyú ; Wade–Giles : Chou Tzu-yü , born June 14, 1999), commonly known by her stage name Tzuyu (Korean : 저우 쯔위 , romanized : Jeo\'u  Jjeu\'wi , Japanese :チョウ・ツウィ, romanized:  Chou Tsuwi ), is a Taiwanese singer . She is the youngest member of the South Korean girl group Twice formed and managed by JYP Entertainment .'},
      // Add more items
    ];

    return itemsData.map((itemData) => Idolkorean.fromMap(itemData)).toList(); // tra ve 1 list cac doi tuong Idolkorean
  }
}